# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: AccBees GWT Platform Maven Package

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      revision:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Publish Version'
        # Default value if no value is explicitly provided
        default: '1.6.1-SNAPSHOT'
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests -Drevision=${{github.event.inputs.revision}}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests -Drevision=${{github.event.inputs.revision}} -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.token }}